version: '3'

services:
    php:
        build: ./php
        networks:
            code-network:
                aliases:
                    - php-server
        dns:
            - ${DNS1}
        volumes:
            - ${CALCULATOR_BASE_PATH}:/src/www/calculator.com:rw,cached
            - ${DOCKER_BASE_PATH}php/php.ini:/usr/local/etc/php/php.ini:ro
            - ${DOCKER_BASE_PATH}php/apcu.ini:/usr/local/etc/php/conf.d/apcu.ini:ro
            - ${DOCKER_BASE_PATH}php/docker.ini:/usr/local/etc/php/conf.d/docker.ini:ro
        environment:
            PHP_XDEBUG_ENABLED: 1
            XDEBUG_CONFIG: remote_host=10.20.30.1 # sudo ifconfig lo0 alias 10.20.30.1
            PHP_IDE_CONFIG: "serverName=docker"

    nginx:
        image: nginx:latest
        volumes:
            - ${CALCULATOR_BASE_PATH}:/src/www/calculator.com:rw,cached
            - ${DOCKER_BASE_PATH}nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ${DOCKER_BASE_PATH}nginx/servers/calculator.com.conf:/etc/nginx/servers/calculator.com.conf:ro
        networks:
            code-network:
                aliases:
                    - ${CALCULATOR_DOMAIN}
        dns:
            - ${DNS1}
        ports:
            - "80:80"

networks:
    code-network:
        driver: bridge
